### ISSUE TITLE
Propose Logo

### ISSUE THREAD

**Issue by mirzazulfan** [davidrjenni/A#8]
Hi @davidrjenni . I'm a graphic designer and an open source enthusiast. I've designed a logo for you and it's free. What do you think? if you need anything change, please let me know. 
Best Regard. [Mirza Zulfan](https://github.com/mirzazulfan/Portfolio/blob/master/README.md)
![a](https://user-images.githubusercontent.com/36124339/44637838-c606c880-a9dd-11e8-96c5-d85dbea07195.png)

**Comment by davidrjenni** [comment]
@mirzazulfan, thank you, this is great.
I like the logo on the left better :)

**Comment by mirzazulfan** [comment]
Thank for your response @davidrjenni . Should i create a pr and upload all files ?

**Comment by davidrjenni** [comment]
@mirzazulfan, yes please. Maybe you could also add it to the readme? Thank you.

**Comment by mirzazulfan** [comment]
Sure. Thank you :) .. I'll add it tomorrow.

**Comment by mirzazulfan** [comment]
Hi @davidrjenni  .. Here's your [files](https://drive.google.com/drive/folders/1OKoxOI2Lk3JKHQjbfBWwN88u5hFvjzEj?ogsrc=32) . Please check #9. If you need anything change in the future, dont hesitate to cantact me. Email : mirzazulfan@gmail.com. I am glad to help your project. 
Have a nice day.

**Comment by davidrjenni** [comment]
Thank you a lot for taking the time :+1:.
I will close this issue and merge your PR.
